apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gpu-orchestrator

resources:
  - resources/gpu-orchestrator.namespace.yaml
  - resources/gpu-orchestrator.serviceaccount.yaml
  - resources/gpu-orchestrator.clusterrole.yaml
  - resources/gpu-orchestrator.deployment.yaml
  - resources/gpu-orchestrator.cloud-tls.certificate.cert-manager.yaml
  - resources/gpu-orchestrator.ingressroute.traefik.yaml
  - resources/gpu-orchestrator.service.yaml

images:
  - name: gpu-orchestrator-image
    newName: ghcr.io/viktis1/gpu-orchestrator
    newTag: "d238c6c06cc5735ed8cd5480b8dc222b2b3ba63b"