#ENC[AES256_GCM,data:7rYbxSpTsSi74xjGfrBNnyechgHkarxk6qk9IdquFPvb5C8iUPtx7Tdhlh8Gn+GfuU19QJBohgwE0OBMXYUgVg==,iv:9wiLTEaKq5A3Sh8cnv14JNrBE3SRUp7Qg65JTdPwTCc=,tag:vqnjRyqXWE2aBl9zWxJAaw==,type:comment]
basic_auth_users:
    promuser: ENC[AES256_GCM,data:rkwWWspaiy5/xJiBtbFJgpH6tkM/eA8eC6oAgbS7cGSdxeOYSzKFrifll3cMRxmvI6tfoC0NFdoy1kLd,iv:p5FAifoHO3UPb6YkNfiddNCCKOvPLtRfZI0RE3VuGBY=,tag:2nUF0rcer/i0g+5s1uVYFg==,type:str]
    prometricsjob: ENC[AES256_GCM,data:rM7iPeRj5+W+kVhozjl8CBEwhB2RecGca1xqBXAhGiAQKtfZXkJyAvVnQehGhBwIAEjj2664M15lbVm4,iv:4GxUOGw/dLTxrxRQUQn5XhxK5vl2a8WQ6C5rMArEsvM=,tag:1focgmO53ZPf+deQc0xDjA==,type:str]
    grafuser: ENC[AES256_GCM,data:gTF62NB0R/34xHV/8gMHkoDLmFR5KGGNwKs9gBTIR/Ky+HmAW3oVFrj0N7c92ILs3Qs/zn/vftTW41T6,iv:YOLPUZwNA5OI8/AMohpFMECPh5mk81ouVENfpLm5DQY=,tag:d6E83d/XAEq16HWqq6NnqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdHA2OW9VVVNydEUxcUFM
            T21qRm1PUEhWMU9qa0o5bkJ2ZE5MRGtuMTBFCnpXWVJKNHBaUW1CMDd5ZnBtQmov
            dTNGYjFSNG11OFF5cm85cXVPYnhOTGsKLS0tIFRteWg2Tm9OUUNicnVnZHZuSmFM
            WHdRa1VvWGJVOTBsOWdoL0FRWElpaTQKoVmMUKdkD29CEWNYXM75q7EfxBguN8nI
            +j37P8JknWFu4UXRJGiL6nqAXWWAUk8OpGUsW65ntpjWxALXgp3DNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rlr90g87ww9q74jhd72jkj3tjqntgjdvajsyswhtevjm8qv2kuys30yw60
    lastmodified: "2026-09-30T18:30:45Z"
    mac: ENC[AES256_GCM,data:3/TUBakbnaGSBBeWMmogRBx5vTU2S3+WOmi58RA36XSIQS3X6K0LU+YfyBlQPNnyMxBmcssRz4A+WaJO8Y3GCLo2B+etX1M89YvpG5tkxFTCzWCP3jSv6HcC93oZA2XVd6b0qEp4c+cET1rZ+UzeTJ9zkTaJGkgbSiFsS0mnwus=,iv:oqJuN6GzHkRI4xxzCStcuoM+fcUEl83HEOY6BdF01ck=,tag:k5s/V79ChFDTQThZdyDp7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
