apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-state-writer
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - tailscale-state
    verbs:
      - get
      - update
      - patch
