# Certificate for root CA
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: viktor.cloud-root-ca-tls
  namespace: cert-manager
spec:
  isCA: true
  commonName: viktor.cloud-root-ca-tls
  secretName: viktor.cloud-root-ca-tls
  duration: 8760h # 1 year
  renewBefore: 720h # Certificates must be renewed some time before they expire (30 days)
  privateKey:
    algorithm: ECDSA
    size: 521
    encoding: PKCS8
    rotationPolicy: Always
  issuerRef:
    name: viktor.cloud-root-ca-issuer-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
