apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/cloud-ingest.deployment.yaml

images:
  - name: cloud-ingest-image
    newName: ghcr.io/viktis1/create-ringtone-cloud-ingest
    newTag: "cdeb24ef9eaeeff50cdc664df31ef4e46b2fd53a"

secretGenerator:
- name: gcp-sa-credentials
  files:
  - resources/gcp-ingest-secret.json