apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/cloud-ingest.serviceaccount.yaml
  - resources/cloud-ingest.deployment.yaml

configMapGenerator:
  - name: gcp-workload-identity
    files:
      - resources/credential-configuration.json
