# Persistent storage volume for garmin login data
apiVersion: v1
kind: PersistentVolume

metadata:
  name: garmin-fetch-data
spec:
  capacity:
    storage: 124Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/garmin/garmin-fetch-data/k3smnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3sagent02
