apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

resources:
  - resources/tailscale.namespace.yaml
  - resources/tailscale-state.secret.yaml
  - resources/tailscale.serviceaccount.yaml
  - resources/tailscale.role.yaml
  - resources/tailscale.rolebinding.yaml
  - resources/tailscale.deployment.yaml

secretGenerator:
  - name: tailscale-auth
    envs:
      - secrets/tailscale-auth.env

images:
  - name: tailscale-image
    newname: tailscale/tailscale
    newTag: "v1.98.10"

generatorOptions:
  disableNameSuffixHash: true
