apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare

resources:
  - resources/cloudflare.secret.yaml
  - resources/cloudflare.deployment.yaml
  - resources/cloudflare.namespace.yaml


images:
- name: cloudflared-image
  newName: cloudflare/cloudflared
  newTag: "latest"