apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: create-ringtone-rustfs
  resources:
    requests:
      storage: 10000Mi