apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rustfs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rustfs
    spec:
      containers:
        - name: rustfs
          image: rustfs/rustfs:1.0.0
          env:
            - name: RUSTFS_VOLUMES
              value: /data
            - name: RUSTFS_ADDRESS
              value: ":9000"
            # just for testing...
            - name: RUSTFS_CONSOLE_ADDRESS
              value: ":9001"
            - name: RUSTFS_CONSOLE_ENABLE
              value: "true"
            #
            - name: RUSTFS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs
                  key: access-key
            - name: RUSTFS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs
                  key: secret-key
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: "1000m"
              memory: "256Mi"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rustfs