apiVersion: ENC[AES256_GCM,data:NRQ=,iv:m5bGRr+nrCrr6bK2FjaTa3Sk+c1EBeTtYjwgbnPoAJo=,tag:2W4+Dr63aArPdMYnT3d4Jg==,type:str]
kind: ENC[AES256_GCM,data:QJl4Pvcq,iv:Kox/T0SWGu9KeeKe2j87RU70vq3ocxm330kH72rj5ac=,tag:mzZjgw5xKF0tguAMaeFUJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/gexIuyO,iv:Oc7dMGqJIfZ9E9ZXwZPzr84P9UXhSgY4dJT0F/TUwnY=,tag:LrP/ntIQEEDgI6PyWS6YMw==,type:str]
type: ENC[AES256_GCM,data:yVhxxxAk,iv:soVZI2R1ECIypJFtocpR1BGY5LEYHVYknTdpE1FFNMg=,tag:6OEjNVvVB8N18yjdHLdUNQ==,type:str]
stringData:
    access-key: ENC[AES256_GCM,data:/2Vf85GQM+t2OzImqCXyD8Q=,iv:4jiizgTDkOWRCnstjxEWVd9A94YBnvwJUOu26yz26qw=,tag:Cd0oTjTGCsmyNw8JQ3hiEA==,type:str]
    secret-key: ENC[AES256_GCM,data:Nevm6HuJ/USSkvCa5WKrnSVi,iv:DCJZ6E7wOd8zm4+fN67em90vL97TfxJmyQOnY07mnJ4=,tag:4ulQCePSq6TXb8xip0gjaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R0pGRm0rajZ0SUcxWlph
            ZUpvbStUS1AvbjRBazJjb3QweEVOSzZhODBZCldEaFpycDRqZU10SFhoRzNKS0pw
            MTFHU1hyNkVrVURwL2xGWjYyUlR1YWcKLS0tIGRhUnNteFR6b3pwK0tmWFJ4NkI2
            UlBmejZ3eXBVZVZlOHNCZURsVzNxRVEKBWd3mKDqmsJLaTkWqLWhOG991TC01Cek
            OkYyhwxVoJc9DZoG299grAGJipKy+mgrKkW/qRww5mV7fQ8vQn3pRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rlr90g87ww9q74jhd72jkj3tjqntgjdvajsyswhtevjm8qv2kuys30yw60
    lastmodified: "2026-09-30T18:22:40Z"
    mac: ENC[AES256_GCM,data:AGvCIvD/rdyATWyhi7/48bINbnVdlRkEBeV+sbmBNYLFEp1UhtnSUPyV716l0YuHplEG9mraNvmGdTfcM6T00x9h30OsTByVK1uKk0GanBxS7EZJjImo9hs41MmJ0QnUsdEU8v5SkxrwTuLy8ghIc28YRQm6vz7105PuCVwR08g=,iv:rq3BwYYGUPTZPRv13qyxKLpB4SDbYO3DR2/C6qgPYDs=,tag:Kbrm6lZ8aadK9vJwb/x9Sw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
