# Local storage contain the GGUF model files for llama.cpp
apiVersion: v1
kind: PersistentVolume

metadata:
  name: llm-nvme-models
spec:
  capacity:
    storage: 99Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/llm-nvme/models/k3smnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3sagent03
