apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ingest

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloud-ingest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloud-ingest
    spec:
      containers:
        - name: cloud-ingest
          image: cloud-ingest-image
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: GOOGLE_CLOUD_PROJECT
              value: ringtone-k8s
            - name: PUBSUB_SUBSCRIPTION
              value: voice-upload-ingest
            - name: RUSTFS_BUCKET
              value: voice-upload
            - name: RUSTFS_ENDPOINT
              value: http://rustfs:9000
            # Access keys
            - name: RUSTFS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs
                  key: access-key
            - name: RUSTFS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs
                  key: secret-key
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/workload-identity/credential-configuration.json
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          volumeMounts:
            - name: gcp-token
              readOnly: true
              mountPath: /var/run/service-account
            - name: gcp-credentials
              mountPath: /etc/workload-identity
              readOnly: true
      serviceAccountName: cloud-ingest
      volumes:
        - name: gcp-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: https://iam.googleapis.com/projects/1094530592033/locations/global/workloadIdentityPools/homelab/providers/k3s-homelab
                  expirationSeconds: 3600
                  path: token
        - name: gcp-credentials
          configMap:
            name: gcp-workload-identity