apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: create-ringtone

resources:
- resources/create-ringtone.namespace.yaml
- resources/create-ringtone-rustfs.pv.yaml
- components/object-storage
- components/cloud-ingest
- components/orchestrator


images:
- name: rustfs
  newTag: 1.0.0

- name: cloud-ingest-image
  newName: ghcr.io/viktis1/create-ringtone-cloud-ingest
  newTag: "6f29a9dae4dea1e4fdeb7887a7606d6b3eb08eb6"

- name: create-ringtone-orchestrator-image
  newName: ghcr.io/viktis1/create-ringtone-orchestrator
  newTag: "6f29a9dae4dea1e4fdeb7887a7606d6b3eb08eb6"