apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: create-ringtone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
    spec:
      containers:
        - name: cloudflare
          image: cloudflared-image
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-token
                  key: token
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --loglevel
            - info
            - --metrics
            - 0.0.0.0:2000
            - run
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to Cloudflare's network.
              path: /ready
              port: 2000
            initialDelaySeconds: 10
            periodSeconds: 10