apiVersion: ENC[AES256_GCM,data:2Cc=,iv:Hza3PLTAlCrMxMTBXocLTTcKNYRjcr/uU5v4Afd4/TA=,tag:KXOcFeXuwRkS88xSRJJuow==,type:str]
kind: ENC[AES256_GCM,data:TbGFSnjv,iv:2+v4dZwveALZbL/hIV8hi2cXbnLyBuspSIDugMrMhcA=,tag:if3Ud5V9c0JNEYFU2G0xKg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:J9tM/4ySSjjRKAEtDGPvRw==,iv:rKq6slljjHZNgFMq64a8tzsDGSB4iIFV7S1i23HQt7o=,tag:Cu5oj/4QqRK/OrapqMuZiw==,type:str]
type: ENC[AES256_GCM,data:lOE6ZtGo,iv:ckuUzq+7RXCrreExSk8ozX/GAE14h0VPzF6Tlh1gyQQ=,tag:HO0s9jPUq56xA21bNm/iKg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:lPXrKLVloz6N9u9+tBktJR7HNhncOx6TK0++Z3h4kWbDTlZJCcz829aGA4KG2TfORZPz3X4vbFU8rYA5Ux7A0RZyQlWLkh53o1onHEjggJQNBafJGiDw6UyZj/g7DMQxRLCMMsFlglujf8SeRv+tirKyXegIVc86tYVv1DORl7kRB1EpH4xSeYbgre/sWC/kM1Q/YkdIaK4hbZgs1so4Hx0M/fzvC6ilCVMwWWGImsABuUdH5M6TntCPHSv/BeSnFZdMGDKN6LZddW8XJPdyycq3QSBhaOpuVVqK7e7sQYva9rjTdFU+1BS6uLTMk0Y9,iv:627XhouHeodu9pOup/gxlhii8/7YsZ986gHmybTGXN0=,tag:tO/wKuaFtCEBW0lgGfVw2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNW5ESWpKNW8zbm5CQkdJ
            M0VkS2lpQ2owV0p4MTFoajVEM3o4czVkYVh3Ckg5MGRFaTNqNHR3aDdqMjJmVnBF
            N096eXRweTU0ZGd5N29QOXc2emREekEKLS0tIGk5TFo1bHBqYmtMU09DK1I5ak43
            K2ZDMisvTWwzTEJUSisvRjRHb0grb1UKfPaOh5h9C8Q4kUElY9eAyVcmKDV60Exh
            sDaGXZapcJlgOk6TE53do7Y2XT1XHLproAbmqIg+V3F8bYDOoNgXag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rlr90g87ww9q74jhd72jkj3tjqntgjdvajsyswhtevjm8qv2kuys30yw60
    lastmodified: "2026-09-30T18:18:53Z"
    mac: ENC[AES256_GCM,data:eZtgVmzaDlkY35HhuZ5xakSsIoHdvXnQoLqz3wkkReN6kd4DBwu/V00zdbTNypabK98zgt4atd0VcDRXN1HRFUVtBz3vkwyPX9b1dHCeJA6bl2md7GUqDs0RRd0wUJWXtpwav5EGpoN8eVeNF7Nhhg9Q0J0/c2v6RRxPE4ic72g=,iv:2sbtmTavUjeP87jeP7rGZfTslt7m2wxEYi1btDe+Whs=,tag:nP38gn8DgwT/VqgtgAXKZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
